package vista;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import controlador.Ctrl_categoria;
import controlador.Ctrl_cliente;
import controlador.Ctrl_inicio;
import controlador.Ctrl_producto;
import controlador.Ctrl_proveedor;
import controlador.Ctrl_usuario;
import modelo.Categoria;
import modelo.CategoriaDAO;
import modelo.Cliente;
import modelo.ClienteDAO;
import modelo.Producto;
import modelo.ProductoDAO;
import modelo.Proveedor;
import modelo.ProveedorDAO;
import modelo.Usuario;
import modelo.UsuarioDAO;

public class Menu extends javax.swing.JFrame {

    Usuario user = new Usuario();
    UsuarioDAO userDao = new UsuarioDAO();
    Cliente client = new Cliente();
    ClienteDAO clientDao = new ClienteDAO();
    Categoria cat = new Categoria();
    CategoriaDAO catDao = new CategoriaDAO();
    Proveedor prov = new Proveedor();
    ProveedorDAO provDao = new ProveedorDAO();
    Producto prod = new Producto();
    ProductoDAO prodDao = new ProductoDAO();

    public Menu() {
        initComponents();
        this.setTitle("SalesWave");
//        this.setSize(new Dimension(1080, 700));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Ctrl_inicio controladorInicio = new Ctrl_inicio(this);
        Ctrl_usuario controladorUsuario = new Ctrl_usuario(user, userDao, this);
        Ctrl_cliente controladorCliente = new Ctrl_cliente(client, clientDao, this);
        Ctrl_categoria controladorCategoria = new Ctrl_categoria(cat, catDao, this);
        Ctrl_proveedor controladorProveedor = new Ctrl_proveedor(prov, provDao, this);
        Ctrl_producto controladorProducto = new Ctrl_producto(prod, prodDao, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupUsuarios = new javax.swing.JPopupMenu();
        jMenuEliminarUsuario = new javax.swing.JMenuItem();
        jMenuHabilitarUsuario = new javax.swing.JMenuItem();
        jPopupCliente = new javax.swing.JPopupMenu();
        jMenuEliminarCliente = new javax.swing.JMenuItem();
        jMenuHabilitarCliente = new javax.swing.JMenuItem();
        jPopupCategoria = new javax.swing.JPopupMenu();
        jMenuEliminarCategoria = new javax.swing.JMenuItem();
        jMenuHabilitarCategoria = new javax.swing.JMenuItem();
        jPopupProducto = new javax.swing.JPopupMenu();
        jMenuEliminarProd = new javax.swing.JMenuItem();
        jMenuHabilitarProd = new javax.swing.JMenuItem();
        jPopupProveedor = new javax.swing.JPopupMenu();
        jMenuEliminarProv = new javax.swing.JMenuItem();
        jMenuHabilitarProv = new javax.swing.JMenuItem();
        jTabbedPanel = new javax.swing.JTabbedPane();
        panelBienvenida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        jScrollUsuario = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        labelPasswrord = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        labelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        labelBuscarUsuario = new javax.swing.JLabel();
        textBuscarUsuario = new javax.swing.JTextField();
        textIdUsuario = new javax.swing.JTextField();
        btn_modificarUsuario = new javax.swing.JButton();
        btn_registrarUsuario = new javax.swing.JButton();
        btn_limpiarUsuario = new javax.swing.JButton();
        labelTelefono1 = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        panelProducto = new javax.swing.JPanel();
        textNombreProd = new javax.swing.JTextField();
        textDescripcionProd = new javax.swing.JTextField();
        textPrecioCProd = new javax.swing.JTextField();
        textPrecioVProd = new javax.swing.JTextField();
        textCantidadProd = new javax.swing.JTextField();
        textBuscarProd = new javax.swing.JTextField();
        textIdProd = new javax.swing.JTextField();
        labelProveedorProd = new javax.swing.JLabel();
        labelDescripcionProd = new javax.swing.JLabel();
        labelPrecioVProd = new javax.swing.JLabel();
        labelIvaProd = new javax.swing.JLabel();
        btn_registrarProd = new javax.swing.JButton();
        btn_modificarProd = new javax.swing.JButton();
        btn_irStock = new javax.swing.JButton();
        labelBuscarProd = new javax.swing.JLabel();
        jScrollProducto = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        labelPrecioCProd1 = new javax.swing.JLabel();
        labelPrecioVProd1 = new javax.swing.JLabel();
        labelPrecioVProd2 = new javax.swing.JLabel();
        btn_limpiarProd = new javax.swing.JButton();
        comboBoxIvaProd = new javax.swing.JComboBox<>();
        labelNombreProd = new javax.swing.JLabel();
        labelCantidadProd = new javax.swing.JLabel();
        comboBoxProveedorProd = new javax.swing.JComboBox<>();
        labelCategoriaProd = new javax.swing.JLabel();
        comboBoxCategoriaProd = new javax.swing.JComboBox<>();
        panelCliente = new javax.swing.JPanel();
        textApellidoCliente = new javax.swing.JTextField();
        textCedulaCliente = new javax.swing.JTextField();
        labelTelefonoCliente = new javax.swing.JLabel();
        jScrollCliente = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        labelApellidoCliente = new javax.swing.JLabel();
        textNombreCliente = new javax.swing.JTextField();
        labelNombreCliente = new javax.swing.JLabel();
        textTelefonoCliente = new javax.swing.JTextField();
        labelCedulaCliente = new javax.swing.JLabel();
        btn_modificarCliente = new javax.swing.JButton();
        btn_registrarCliente = new javax.swing.JButton();
        btn_limpiarCliente = new javax.swing.JButton();
        textIdCliente = new javax.swing.JTextField();
        textBuscarCliente = new javax.swing.JTextField();
        labelBuscarCliente = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        textNombreCategoria = new javax.swing.JTextField();
        labelNombreCategoria = new javax.swing.JLabel();
        textIdCategoria = new javax.swing.JTextField();
        btn_registrarCategoria = new javax.swing.JButton();
        btn_limpiarCategoria = new javax.swing.JButton();
        labelBuscarCategoria = new javax.swing.JLabel();
        textBuscarCategoria = new javax.swing.JTextField();
        jScrollCategoria = new javax.swing.JScrollPane();
        tableCategoria = new javax.swing.JTable();
        btn_modificarCategoria = new javax.swing.JButton();
        panelProveedor = new javax.swing.JPanel();
        btn_registrarProv = new javax.swing.JButton();
        btn_limpiarProv = new javax.swing.JButton();
        labelBuscarProv = new javax.swing.JLabel();
        textBuscarProv = new javax.swing.JTextField();
        jScrollProveedor = new javax.swing.JScrollPane();
        tableProveedor = new javax.swing.JTable();
        labelNombreProv = new javax.swing.JLabel();
        textDireccionProv = new javax.swing.JTextField();
        labelApellidoProv = new javax.swing.JLabel();
        textApellidoProv = new javax.swing.JTextField();
        labelTelefonoProv = new javax.swing.JLabel();
        textTelefonoProv = new javax.swing.JTextField();
        labelDireccionProv = new javax.swing.JLabel();
        textNombreProv = new javax.swing.JTextField();
        textIdProv = new javax.swing.JTextField();
        btn_modificarProv = new javax.swing.JButton();
        panelVenta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelReporte = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelActualizarStock = new javax.swing.JPanel();
        labelComboProd = new javax.swing.JLabel();
        comboBoxProductos = new javax.swing.JComboBox<>();
        jScrollStock = new javax.swing.JScrollPane();
        tableStock = new javax.swing.JTable();
        labelCantidadNew = new javax.swing.JLabel();
        textStockAct = new javax.swing.JTextField();
        textStockNew = new javax.swing.JTextField();
        labelCantidadAct = new javax.swing.JLabel();
        btn_actualizarStock = new javax.swing.JButton();
        btn_volverProd = new javax.swing.JButton();
        textIdProdStock = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelEmpresa = new javax.swing.JPanel();
        labelEmpresaNombre = new javax.swing.JLabel();
        labelEmpresaNit = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();

        jMenuEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jMenuEliminarUsuario.setText("Eliminar");
        jMenuEliminarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuEliminarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuEliminarUsuario.setIconTextGap(3);
        jMenuEliminarUsuario.setPreferredSize(new java.awt.Dimension(85, 23));
        jMenuEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarUsuarioActionPerformed(evt);
            }
        });
        jPopupUsuarios.add(jMenuEliminarUsuario);

        jMenuHabilitarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/available.png"))); // NOI18N
        jMenuHabilitarUsuario.setText("Habilitar");
        jMenuHabilitarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuHabilitarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuHabilitarUsuario.setIconTextGap(3);
        jMenuHabilitarUsuario.setPreferredSize(new java.awt.Dimension(85, 23));
        jPopupUsuarios.add(jMenuHabilitarUsuario);

        jMenuEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jMenuEliminarCliente.setText("Eliminar");
        jMenuEliminarCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuEliminarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuEliminarCliente.setIconTextGap(3);
        jMenuEliminarCliente.setPreferredSize(new java.awt.Dimension(85, 23));
        jMenuEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarClienteActionPerformed(evt);
            }
        });
        jPopupCliente.add(jMenuEliminarCliente);

        jMenuHabilitarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/available.png"))); // NOI18N
        jMenuHabilitarCliente.setText("Habilitar");
        jMenuHabilitarCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuHabilitarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuHabilitarCliente.setIconTextGap(3);
        jMenuHabilitarCliente.setPreferredSize(new java.awt.Dimension(85, 23));
        jPopupCliente.add(jMenuHabilitarCliente);

        jMenuEliminarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jMenuEliminarCategoria.setText("Eliminar");
        jMenuEliminarCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuEliminarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuEliminarCategoria.setIconTextGap(3);
        jMenuEliminarCategoria.setPreferredSize(new java.awt.Dimension(85, 23));
        jMenuEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarCategoriaActionPerformed(evt);
            }
        });
        jPopupCategoria.add(jMenuEliminarCategoria);

        jMenuHabilitarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/available.png"))); // NOI18N
        jMenuHabilitarCategoria.setText("Habilitar");
        jMenuHabilitarCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuHabilitarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuHabilitarCategoria.setIconTextGap(3);
        jMenuHabilitarCategoria.setPreferredSize(new java.awt.Dimension(85, 23));
        jPopupCategoria.add(jMenuHabilitarCategoria);

        jMenuEliminarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jMenuEliminarProd.setText("Eliminar");
        jMenuEliminarProd.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuEliminarProd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuEliminarProd.setIconTextGap(3);
        jMenuEliminarProd.setPreferredSize(new java.awt.Dimension(85, 23));
        jMenuEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarProdActionPerformed(evt);
            }
        });
        jPopupProducto.add(jMenuEliminarProd);

        jMenuHabilitarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/available.png"))); // NOI18N
        jMenuHabilitarProd.setText("Habilitar");
        jMenuHabilitarProd.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuHabilitarProd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuHabilitarProd.setIconTextGap(3);
        jMenuHabilitarProd.setPreferredSize(new java.awt.Dimension(85, 23));
        jPopupProducto.add(jMenuHabilitarProd);

        jMenuEliminarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jMenuEliminarProv.setText("Eliminar");
        jMenuEliminarProv.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuEliminarProv.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuEliminarProv.setIconTextGap(3);
        jMenuEliminarProv.setPreferredSize(new java.awt.Dimension(85, 23));
        jMenuEliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarProvActionPerformed(evt);
            }
        });
        jPopupProveedor.add(jMenuEliminarProv);

        jMenuHabilitarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/available.png"))); // NOI18N
        jMenuHabilitarProv.setText("Habilitar");
        jMenuHabilitarProv.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuHabilitarProv.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuHabilitarProv.setIconTextGap(3);
        jMenuHabilitarProv.setPreferredSize(new java.awt.Dimension(85, 23));
        jPopupProveedor.add(jMenuHabilitarProv);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPanel.setMinimumSize(new java.awt.Dimension(880, 700));
        jTabbedPanel.setPreferredSize(new java.awt.Dimension(880, 700));

        panelBienvenida.setPreferredSize(new java.awt.Dimension(870, 670));
        panelBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("inicio");
        panelBienvenida.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 221, -1, -1));

        jTabbedPanel.addTab("inicio", panelBienvenida);

        panelUsuario.setPreferredSize(new java.awt.Dimension(880, 700));
        panelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableUsuarios.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Usuario", "Telefono", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.setComponentPopupMenu(jPopupUsuarios);
        tableUsuarios.setRowHeight(30);
        tableUsuarios.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tableUsuarios.getTableHeader().setResizingAllowed(false);
        tableUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollUsuario.setViewportView(tableUsuarios);

        panelUsuario.add(jScrollUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 840, 353));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(51, 51, 51));
        labelNombre.setText("Nombre");
        panelUsuario.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        textNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textNombre.setForeground(new java.awt.Color(51, 51, 51));
        textNombre.setPreferredSize(new java.awt.Dimension(160, 30));
        panelUsuario.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        labelApellido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelApellido.setForeground(new java.awt.Color(51, 51, 51));
        labelApellido.setText("Apellido");
        panelUsuario.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, -1, 30));

        textApellido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textApellido.setForeground(new java.awt.Color(51, 51, 51));
        textApellido.setPreferredSize(new java.awt.Dimension(160, 30));
        panelUsuario.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        labelPasswrord.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelPasswrord.setForeground(new java.awt.Color(51, 51, 51));
        labelPasswrord.setText("Contraseña");
        panelUsuario.add(labelPasswrord, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 60, -1, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setPreferredSize(new java.awt.Dimension(170, 30));
        panelUsuario.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(51, 51, 51));
        labelUsuario.setText("Usuario");
        panelUsuario.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 120, -1, 30));

        textUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(51, 51, 51));
        textUsuario.setPreferredSize(new java.awt.Dimension(160, 30));
        panelUsuario.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(51, 51, 51));
        labelTelefono.setText("Telefono");
        panelUsuario.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 180, -1, 30));

        textTelefono.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textTelefono.setForeground(new java.awt.Color(51, 51, 51));
        textTelefono.setPreferredSize(new java.awt.Dimension(160, 30));
        panelUsuario.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        labelBuscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelBuscarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        labelBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        labelBuscarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelUsuario.add(labelBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        textBuscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textBuscarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        textBuscarUsuario.setPreferredSize(new java.awt.Dimension(160, 30));
        panelUsuario.add(textBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        textIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textIdUsuario.setForeground(new java.awt.Color(51, 51, 51));
        textIdUsuario.setPreferredSize(new java.awt.Dimension(160, 30));
        panelUsuario.add(textIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, -1));

        btn_modificarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificarUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_modificarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        btn_modificarUsuario.setText("Modificar");
        btn_modificarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 158, 67), 2));
        btn_modificarUsuario.setPreferredSize(new java.awt.Dimension(90, 30));
        panelUsuario.add(btn_modificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 100, -1));

        btn_registrarUsuario.setBackground(new java.awt.Color(232, 158, 67));
        btn_registrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_registrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarUsuario.setText("Registrar");
        btn_registrarUsuario.setPreferredSize(new java.awt.Dimension(100, 30));
        panelUsuario.add(btn_registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        btn_limpiarUsuario.setBackground(new java.awt.Color(232, 158, 67));
        btn_limpiarUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_limpiarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarUsuario.setText("Limpiar");
        btn_limpiarUsuario.setPreferredSize(new java.awt.Dimension(90, 30));
        btn_limpiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarUsuarioActionPerformed(evt);
            }
        });
        panelUsuario.add(btn_limpiarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        labelTelefono1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTelefono1.setForeground(new java.awt.Color(51, 51, 51));
        labelTelefono1.setText("Correo");
        panelUsuario.add(labelTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 30));

        textCorreo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textCorreo.setForeground(new java.awt.Color(51, 51, 51));
        textCorreo.setToolTipText("");
        textCorreo.setPreferredSize(new java.awt.Dimension(160, 30));
        textCorreo.setSelectionColor(new java.awt.Color(191, 232, 241));
        textCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCorreoActionPerformed(evt);
            }
        });
        panelUsuario.add(textCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 240, -1));

        jTabbedPanel.addTab("usuario", panelUsuario);

        panelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNombreProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textNombreProd.setForeground(new java.awt.Color(51, 51, 51));
        textNombreProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(textNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, -1));

        textDescripcionProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textDescripcionProd.setForeground(new java.awt.Color(51, 51, 51));
        textDescripcionProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(textDescripcionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 410, -1));

        textPrecioCProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textPrecioCProd.setForeground(new java.awt.Color(51, 51, 51));
        textPrecioCProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(textPrecioCProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        textPrecioVProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textPrecioVProd.setForeground(new java.awt.Color(51, 51, 51));
        textPrecioVProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(textPrecioVProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        textCantidadProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textCantidadProd.setForeground(new java.awt.Color(51, 51, 51));
        textCantidadProd.setPreferredSize(new java.awt.Dimension(120, 30));
        panelProducto.add(textCantidadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 90, -1));

        textBuscarProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textBuscarProd.setForeground(new java.awt.Color(51, 51, 51));
        textBuscarProd.setPreferredSize(new java.awt.Dimension(160, 30));
        textBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarProdActionPerformed(evt);
            }
        });
        panelProducto.add(textBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        textIdProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textIdProd.setForeground(new java.awt.Color(51, 51, 51));
        textIdProd.setPreferredSize(new java.awt.Dimension(120, 30));
        panelProducto.add(textIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, -1));

        labelProveedorProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelProveedorProd.setForeground(new java.awt.Color(51, 51, 51));
        labelProveedorProd.setText("Proveedor");
        panelProducto.add(labelProveedorProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 60, -1, 30));

        labelDescripcionProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelDescripcionProd.setForeground(new java.awt.Color(51, 51, 51));
        labelDescripcionProd.setText("Descripcion");
        panelProducto.add(labelDescripcionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        labelPrecioVProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelPrecioVProd.setForeground(new java.awt.Color(51, 51, 51));
        labelPrecioVProd.setText("Compra");
        panelProducto.add(labelPrecioVProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 177, -1, -1));

        labelIvaProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelIvaProd.setForeground(new java.awt.Color(51, 51, 51));
        labelIvaProd.setText("Iva");
        panelProducto.add(labelIvaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, 30));

        btn_registrarProd.setBackground(new java.awt.Color(232, 158, 67));
        btn_registrarProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_registrarProd.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarProd.setText("Registrar");
        btn_registrarProd.setPreferredSize(new java.awt.Dimension(100, 30));
        panelProducto.add(btn_registrarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        btn_modificarProd.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificarProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_modificarProd.setForeground(new java.awt.Color(51, 51, 51));
        btn_modificarProd.setText("Modificar");
        btn_modificarProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 158, 67), 2));
        btn_modificarProd.setPreferredSize(new java.awt.Dimension(90, 30));
        panelProducto.add(btn_modificarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 100, -1));

        btn_irStock.setBackground(new java.awt.Color(232, 158, 67));
        btn_irStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_irStock.setForeground(new java.awt.Color(255, 255, 255));
        btn_irStock.setText("Stock");
        btn_irStock.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_irStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_irStockActionPerformed(evt);
            }
        });
        panelProducto.add(btn_irStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        labelBuscarProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelBuscarProd.setForeground(new java.awt.Color(51, 51, 51));
        labelBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        labelBuscarProd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelProducto.add(labelBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        tableProducto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableProducto.setForeground(new java.awt.Color(51, 51, 51));
        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Cantidad", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProducto.setComponentPopupMenu(jPopupProducto);
        tableProducto.setRowHeight(30);
        tableProducto.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tableProducto.getTableHeader().setResizingAllowed(false);
        tableProducto.getTableHeader().setReorderingAllowed(false);
        jScrollProducto.setViewportView(tableProducto);

        panelProducto.add(jScrollProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 840, 353));

        labelPrecioCProd1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelPrecioCProd1.setForeground(new java.awt.Color(51, 51, 51));
        labelPrecioCProd1.setText("Precio");
        panelProducto.add(labelPrecioCProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 157, -1, -1));

        labelPrecioVProd1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelPrecioVProd1.setForeground(new java.awt.Color(51, 51, 51));
        labelPrecioVProd1.setText("Precio");
        panelProducto.add(labelPrecioVProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 157, -1, -1));

        labelPrecioVProd2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelPrecioVProd2.setForeground(new java.awt.Color(51, 51, 51));
        labelPrecioVProd2.setText("Venta");
        panelProducto.add(labelPrecioVProd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 177, -1, -1));

        btn_limpiarProd.setBackground(new java.awt.Color(232, 158, 67));
        btn_limpiarProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_limpiarProd.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarProd.setText("Limpiar");
        btn_limpiarProd.setPreferredSize(new java.awt.Dimension(90, 30));
        panelProducto.add(btn_limpiarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        comboBoxIvaProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboBoxIvaProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione iva", "No agrava iva", "5%", "19%" }));
        comboBoxIvaProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(comboBoxIvaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 110, -1));

        labelNombreProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNombreProd.setForeground(new java.awt.Color(51, 51, 51));
        labelNombreProd.setText("Nombre");
        panelProducto.add(labelNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        labelCantidadProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelCantidadProd.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidadProd.setText("Cantidad");
        panelProducto.add(labelCantidadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 160, -1, 30));

        comboBoxProveedorProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboBoxProveedorProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(comboBoxProveedorProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 190, -1));

        labelCategoriaProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelCategoriaProd.setForeground(new java.awt.Color(51, 51, 51));
        labelCategoriaProd.setText("Categoria");
        labelCategoriaProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelProducto.add(labelCategoriaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 60, -1, 30));

        comboBoxCategoriaProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboBoxCategoriaProd.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProducto.add(comboBoxCategoriaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 60, 200, -1));

        jTabbedPanel.addTab("producto", panelProducto);

        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textApellidoCliente.setForeground(new java.awt.Color(51, 51, 51));
        textApellidoCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCliente.add(textApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 60, -1, -1));

        textCedulaCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textCedulaCliente.setForeground(new java.awt.Color(51, 51, 51));
        textCedulaCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCliente.add(textCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        labelTelefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTelefonoCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelTelefonoCliente.setText("Telefono");
        panelCliente.add(labelTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 120, -1, 30));

        tableCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableCliente.setForeground(new java.awt.Color(51, 51, 51));
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Cedula", "Telefono", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCliente.setComponentPopupMenu(jPopupCliente);
        tableCliente.setRowHeight(30);
        tableCliente.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tableCliente.setShowGrid(false);
        tableCliente.getTableHeader().setResizingAllowed(false);
        tableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollCliente.setViewportView(tableCliente);

        panelCliente.add(jScrollCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 840, 353));

        labelApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelApellidoCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelApellidoCliente.setText("Apellido");
        panelCliente.add(labelApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 60, -1, 30));

        textNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textNombreCliente.setForeground(new java.awt.Color(51, 51, 51));
        textNombreCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCliente.add(textNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        labelNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNombreCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelNombreCliente.setText("Nombre");
        panelCliente.add(labelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        textTelefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textTelefonoCliente.setForeground(new java.awt.Color(51, 51, 51));
        textTelefonoCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCliente.add(textTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        labelCedulaCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelCedulaCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelCedulaCliente.setText("Cedula");
        panelCliente.add(labelCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, 30));

        btn_modificarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificarCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_modificarCliente.setForeground(new java.awt.Color(51, 51, 51));
        btn_modificarCliente.setText("Modificar");
        btn_modificarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 158, 67), 2));
        btn_modificarCliente.setPreferredSize(new java.awt.Dimension(90, 30));
        panelCliente.add(btn_modificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 100, -1));

        btn_registrarCliente.setBackground(new java.awt.Color(232, 158, 67));
        btn_registrarCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_registrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarCliente.setText("Registrar");
        btn_registrarCliente.setPreferredSize(new java.awt.Dimension(100, 30));
        panelCliente.add(btn_registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        btn_limpiarCliente.setBackground(new java.awt.Color(232, 158, 67));
        btn_limpiarCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_limpiarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarCliente.setText("Limpiar");
        btn_limpiarCliente.setPreferredSize(new java.awt.Dimension(90, 30));
        panelCliente.add(btn_limpiarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        textIdCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textIdCliente.setForeground(new java.awt.Color(51, 51, 51));
        textIdCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCliente.add(textIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, -1));

        textBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textBuscarCliente.setForeground(new java.awt.Color(51, 51, 51));
        textBuscarCliente.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCliente.add(textBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        labelBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelBuscarCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        labelBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelCliente.add(labelBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jTabbedPanel.addTab("cliente", panelCliente);

        panelCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNombreCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textNombreCategoria.setForeground(new java.awt.Color(51, 51, 51));
        textNombreCategoria.setPreferredSize(new java.awt.Dimension(300, 30));
        panelCategoria.add(textNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        labelNombreCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNombreCategoria.setForeground(new java.awt.Color(51, 51, 51));
        labelNombreCategoria.setText("Nombre");
        panelCategoria.add(labelNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        textIdCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textIdCategoria.setForeground(new java.awt.Color(51, 51, 51));
        textIdCategoria.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCategoria.add(textIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 60, -1));

        btn_registrarCategoria.setBackground(new java.awt.Color(232, 158, 67));
        btn_registrarCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_registrarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarCategoria.setText("Registrar");
        btn_registrarCategoria.setPreferredSize(new java.awt.Dimension(100, 30));
        panelCategoria.add(btn_registrarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        btn_limpiarCategoria.setBackground(new java.awt.Color(232, 158, 67));
        btn_limpiarCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_limpiarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarCategoria.setText("Limpiar");
        btn_limpiarCategoria.setPreferredSize(new java.awt.Dimension(90, 30));
        panelCategoria.add(btn_limpiarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        labelBuscarCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelBuscarCategoria.setForeground(new java.awt.Color(51, 51, 51));
        labelBuscarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        labelBuscarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelCategoria.add(labelBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        textBuscarCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textBuscarCategoria.setForeground(new java.awt.Color(51, 51, 51));
        textBuscarCategoria.setPreferredSize(new java.awt.Dimension(160, 30));
        panelCategoria.add(textBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        tableCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableCategoria.setForeground(new java.awt.Color(51, 51, 51));
        tableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCategoria.setComponentPopupMenu(jPopupCategoria);
        tableCategoria.setRowHeight(30);
        tableCategoria.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tableCategoria.getTableHeader().setResizingAllowed(false);
        tableCategoria.getTableHeader().setReorderingAllowed(false);
        jScrollCategoria.setViewportView(tableCategoria);

        panelCategoria.add(jScrollCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 840, 353));

        btn_modificarCategoria.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificarCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_modificarCategoria.setForeground(new java.awt.Color(51, 51, 51));
        btn_modificarCategoria.setText("Modificar");
        btn_modificarCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 158, 67), 2));
        btn_modificarCategoria.setPreferredSize(new java.awt.Dimension(90, 30));
        panelCategoria.add(btn_modificarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 100, -1));

        jTabbedPanel.addTab("categoria", panelCategoria);

        panelProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrarProv.setBackground(new java.awt.Color(232, 158, 67));
        btn_registrarProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_registrarProv.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarProv.setText("Registrar");
        btn_registrarProv.setPreferredSize(new java.awt.Dimension(100, 30));
        panelProveedor.add(btn_registrarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        btn_limpiarProv.setBackground(new java.awt.Color(232, 158, 67));
        btn_limpiarProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_limpiarProv.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarProv.setText("Limpiar");
        btn_limpiarProv.setPreferredSize(new java.awt.Dimension(90, 30));
        panelProveedor.add(btn_limpiarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        labelBuscarProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelBuscarProv.setForeground(new java.awt.Color(51, 51, 51));
        labelBuscarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        labelBuscarProv.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelProveedor.add(labelBuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        textBuscarProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textBuscarProv.setForeground(new java.awt.Color(51, 51, 51));
        textBuscarProv.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProveedor.add(textBuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        tableProveedor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableProveedor.setForeground(new java.awt.Color(51, 51, 51));
        tableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProveedor.setComponentPopupMenu(jPopupProveedor);
        tableProveedor.setRowHeight(30);
        tableProveedor.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tableProveedor.getTableHeader().setResizingAllowed(false);
        tableProveedor.getTableHeader().setReorderingAllowed(false);
        jScrollProveedor.setViewportView(tableProveedor);

        panelProveedor.add(jScrollProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 840, 353));

        labelNombreProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNombreProv.setForeground(new java.awt.Color(51, 51, 51));
        labelNombreProv.setText("Nombre");
        panelProveedor.add(labelNombreProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        textDireccionProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textDireccionProv.setForeground(new java.awt.Color(51, 51, 51));
        textDireccionProv.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProveedor.add(textDireccionProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 400, -1));

        labelApellidoProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelApellidoProv.setForeground(new java.awt.Color(51, 51, 51));
        labelApellidoProv.setText("Apellido");
        panelProveedor.add(labelApellidoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 60, -1, 30));

        textApellidoProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textApellidoProv.setForeground(new java.awt.Color(51, 51, 51));
        textApellidoProv.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProveedor.add(textApellidoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        labelTelefonoProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTelefonoProv.setForeground(new java.awt.Color(51, 51, 51));
        labelTelefonoProv.setText("Telefono");
        panelProveedor.add(labelTelefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 60, -1, 30));

        textTelefonoProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textTelefonoProv.setForeground(new java.awt.Color(51, 51, 51));
        textTelefonoProv.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProveedor.add(textTelefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        labelDireccionProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelDireccionProv.setForeground(new java.awt.Color(51, 51, 51));
        labelDireccionProv.setText("Direccion");
        panelProveedor.add(labelDireccionProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 120, -1, 30));

        textNombreProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textNombreProv.setForeground(new java.awt.Color(51, 51, 51));
        textNombreProv.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProveedor.add(textNombreProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        textIdProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textIdProv.setForeground(new java.awt.Color(51, 51, 51));
        textIdProv.setPreferredSize(new java.awt.Dimension(160, 30));
        panelProveedor.add(textIdProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 40, -1));

        btn_modificarProv.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificarProv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_modificarProv.setForeground(new java.awt.Color(51, 51, 51));
        btn_modificarProv.setText("Modificar");
        btn_modificarProv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 158, 67), 2));
        btn_modificarProv.setPreferredSize(new java.awt.Dimension(90, 30));
        panelProveedor.add(btn_modificarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 100, -1));

        jTabbedPanel.addTab("proveedor", panelProveedor);

        jLabel3.setText("venta");

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel3)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel3)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("venta", panelVenta);

        jLabel4.setText("reporte");

        javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
        panelReporte.setLayout(panelReporteLayout);
        panelReporteLayout.setHorizontalGroup(
            panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel4)
                .addContainerGap(643, Short.MAX_VALUE))
        );
        panelReporteLayout.setVerticalGroup(
            panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel4)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("reporte", panelReporte);

        panelActualizarStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelComboProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelComboProd.setForeground(new java.awt.Color(51, 51, 51));
        labelComboProd.setText("Productos");
        panelActualizarStock.add(labelComboProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        comboBoxProductos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboBoxProductos.setPreferredSize(new java.awt.Dimension(160, 30));
        panelActualizarStock.add(comboBoxProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 200, -1));

        tableStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableStock.setForeground(new java.awt.Color(51, 51, 51));
        tableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Cantidad", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStock.setRowHeight(30);
        tableStock.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tableStock.getTableHeader().setResizingAllowed(false);
        tableStock.getTableHeader().setReorderingAllowed(false);
        jScrollStock.setViewportView(tableStock);

        panelActualizarStock.add(jScrollStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 278, 840, 353));

        labelCantidadNew.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelCantidadNew.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidadNew.setText("Cantidad Nueva");
        panelActualizarStock.add(labelCantidadNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 30));

        textStockAct.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textStockAct.setForeground(new java.awt.Color(51, 51, 51));
        textStockAct.setPreferredSize(new java.awt.Dimension(120, 30));
        panelActualizarStock.add(textStockAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, -1));

        textStockNew.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textStockNew.setForeground(new java.awt.Color(51, 51, 51));
        textStockNew.setPreferredSize(new java.awt.Dimension(120, 30));
        panelActualizarStock.add(textStockNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 90, -1));

        labelCantidadAct.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelCantidadAct.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidadAct.setText("Cantidad");
        panelActualizarStock.add(labelCantidadAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        btn_actualizarStock.setBackground(new java.awt.Color(232, 158, 67));
        btn_actualizarStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_actualizarStock.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizarStock.setText("Actualizar Stock");
        btn_actualizarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizarStock.setPreferredSize(new java.awt.Dimension(100, 30));
        panelActualizarStock.add(btn_actualizarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 170, -1));

        btn_volverProd.setBackground(new java.awt.Color(232, 158, 67));
        btn_volverProd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_volverProd.setForeground(new java.awt.Color(255, 255, 255));
        btn_volverProd.setActionCommand("Atras");
        btn_volverProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volverProd.setLabel("Atrás");
        btn_volverProd.setPreferredSize(new java.awt.Dimension(100, 30));
        panelActualizarStock.add(btn_volverProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        textIdProdStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textIdProdStock.setForeground(new java.awt.Color(51, 51, 51));
        textIdProdStock.setPreferredSize(new java.awt.Dimension(120, 30));
        panelActualizarStock.add(textIdProdStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 50, -1));

        jTabbedPanel.addTab("stock", panelActualizarStock);

        jLabel5.setText("password");

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasswordLayout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(348, 348, 348))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel5)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("password", panelPassword);

        labelEmpresaNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelEmpresaNombre.setForeground(new java.awt.Color(51, 51, 51));
        labelEmpresaNombre.setText("Nombre");

        labelEmpresaNit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelEmpresaNit.setForeground(new java.awt.Color(51, 51, 51));
        labelEmpresaNit.setText("Nombre");

        javax.swing.GroupLayout panelEmpresaLayout = new javax.swing.GroupLayout(panelEmpresa);
        panelEmpresa.setLayout(panelEmpresaLayout);
        panelEmpresaLayout.setHorizontalGroup(
            panelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpresaLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(panelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmpresaNit)
                    .addComponent(labelEmpresaNombre))
                .addContainerGap(661, Short.MAX_VALUE))
        );
        panelEmpresaLayout.setVerticalGroup(
            panelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpresaLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(labelEmpresaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(labelEmpresaNit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("empresa", panelEmpresa);

        getContentPane().add(jTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        panelMenu.setBackground(new java.awt.Color(0, 161, 199));
        panelMenu.setPreferredSize(new java.awt.Dimension(200, 703));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuario.setBackground(new java.awt.Color(0, 161, 199));
        btnUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setBorderPainted(false);
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuario.setPreferredSize(new java.awt.Dimension(200, 50));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        panelMenu.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, -1, -1));

        btnProducto.setBackground(new java.awt.Color(0, 161, 199));
        btnProducto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/product.png"))); // NOI18N
        btnProducto.setText("Producto");
        btnProducto.setBorderPainted(false);
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducto.setPreferredSize(new java.awt.Dimension(200, 50));
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        panelMenu.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        btnCliente.setBackground(new java.awt.Color(0, 161, 199));
        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/costumer.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setBorderPainted(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCliente.setPreferredSize(new java.awt.Dimension(200, 50));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        panelMenu.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, -1, -1));

        btnProveedor.setBackground(new java.awt.Color(0, 161, 199));
        btnProveedor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/supplier.png"))); // NOI18N
        btnProveedor.setText("Proveedor");
        btnProveedor.setBorderPainted(false);
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedor.setPreferredSize(new java.awt.Dimension(200, 50));
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        panelMenu.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, -1, -1));

        btnVenta.setBackground(new java.awt.Color(0, 161, 199));
        btnVenta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sales.png"))); // NOI18N
        btnVenta.setText("Venta");
        btnVenta.setBorderPainted(false);
        btnVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenta.setPreferredSize(new java.awt.Dimension(200, 50));
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        panelMenu.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        btnEmpresa.setBackground(new java.awt.Color(0, 161, 199));
        btnEmpresa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/company.png"))); // NOI18N
        btnEmpresa.setText("Empresa");
        btnEmpresa.setBorderPainted(false);
        btnEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpresa.setPreferredSize(new java.awt.Dimension(200, 50));
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });
        panelMenu.add(btnEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(0, 161, 199));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logOut.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(200, 50));
        panelMenu.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        btnCategoria.setBackground(new java.awt.Color(0, 161, 199));
        btnCategoria.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/category.png"))); // NOI18N
        btnCategoria.setText("Categoria");
        btnCategoria.setBorderPainted(false);
        btnCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategoria.setPreferredSize(new java.awt.Dimension(200, 50));
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });
        panelMenu.add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btnInicio.setBackground(new java.awt.Color(0, 161, 199));
        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorderPainted(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setPreferredSize(new java.awt.Dimension(200, 50));
        panelMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        btnReporte.setBackground(new java.awt.Color(0, 161, 199));
        btnReporte.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report.png"))); // NOI18N
        btnReporte.setText("Reportes");
        btnReporte.setBorderPainted(false);
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporte.setPreferredSize(new java.awt.Dimension(200, 50));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        panelMenu.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, -1, -1));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHeader.setBackground(new java.awt.Color(0, 161, 199));
        panelHeader.setPreferredSize(new java.awt.Dimension(880, 40));

        tituloPanel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        tituloPanel.setText("Titulo de Panel");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(tituloPanel)
                .addGap(0, 769, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
//        jTabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
//        jTabbedPanel.setSelectedIndex(2);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
//        jTabbedPanel.setSelectedIndex(3);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
//        jTabbedPanel.setSelectedIndex(5);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
//        jTabbedPanel.setSelectedIndex(6);
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
//        jTabbedPanel.setSelectedIndex(7);
    }//GEN-LAST:event_btnEmpresaActionPerformed

    private void jMenuEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarUsuarioActionPerformed

    }//GEN-LAST:event_jMenuEliminarUsuarioActionPerformed

    private void jMenuEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarClienteActionPerformed

    }//GEN-LAST:event_jMenuEliminarClienteActionPerformed

    private void jMenuEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarCategoriaActionPerformed

    }//GEN-LAST:event_jMenuEliminarCategoriaActionPerformed

    private void btn_irStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_irStockActionPerformed
//        jTabbedPanel.setSelectedIndex(8);
    }//GEN-LAST:event_btn_irStockActionPerformed

    private void jMenuEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEliminarProdActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
//        jTabbedPanel.setSelectedIndex(4);
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void jMenuEliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEliminarProvActionPerformed

    private void textBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarProdActionPerformed

    private void textCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorreoActionPerformed

    }//GEN-LAST:event_textCorreoActionPerformed

    private void btn_limpiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarUsuarioActionPerformed

    }//GEN-LAST:event_btn_limpiarUsuarioActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCategoria;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnCliente;
    public javax.swing.JButton btnEmpresa;
    public javax.swing.JButton btnInicio;
    public javax.swing.JButton btnProducto;
    public javax.swing.JButton btnProveedor;
    public javax.swing.JButton btnReporte;
    public javax.swing.JButton btnUsuario;
    public javax.swing.JButton btnVenta;
    public javax.swing.JButton btn_actualizarStock;
    public javax.swing.JButton btn_irStock;
    public javax.swing.JButton btn_limpiarCategoria;
    public javax.swing.JButton btn_limpiarCliente;
    public javax.swing.JButton btn_limpiarProd;
    public javax.swing.JButton btn_limpiarProv;
    public javax.swing.JButton btn_limpiarUsuario;
    public javax.swing.JButton btn_modificarCategoria;
    public javax.swing.JButton btn_modificarCliente;
    public javax.swing.JButton btn_modificarProd;
    public javax.swing.JButton btn_modificarProv;
    public javax.swing.JButton btn_modificarUsuario;
    public javax.swing.JButton btn_registrarCategoria;
    public javax.swing.JButton btn_registrarCliente;
    public javax.swing.JButton btn_registrarProd;
    public javax.swing.JButton btn_registrarProv;
    public javax.swing.JButton btn_registrarUsuario;
    public javax.swing.JButton btn_volverProd;
    public javax.swing.JComboBox<Object> comboBoxCategoriaProd;
    public javax.swing.JComboBox<String> comboBoxIvaProd;
    public javax.swing.JComboBox<Object> comboBoxProductos;
    public javax.swing.JComboBox<Object> comboBoxProveedorProd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JMenuItem jMenuEliminarCategoria;
    public javax.swing.JMenuItem jMenuEliminarCliente;
    public javax.swing.JMenuItem jMenuEliminarProd;
    public javax.swing.JMenuItem jMenuEliminarProv;
    public javax.swing.JMenuItem jMenuEliminarUsuario;
    public javax.swing.JMenuItem jMenuHabilitarCategoria;
    public javax.swing.JMenuItem jMenuHabilitarCliente;
    public javax.swing.JMenuItem jMenuHabilitarProd;
    public javax.swing.JMenuItem jMenuHabilitarProv;
    public javax.swing.JMenuItem jMenuHabilitarUsuario;
    public javax.swing.JPopupMenu jPopupCategoria;
    public javax.swing.JPopupMenu jPopupCliente;
    private javax.swing.JPopupMenu jPopupProducto;
    public javax.swing.JPopupMenu jPopupProveedor;
    public javax.swing.JPopupMenu jPopupUsuarios;
    private javax.swing.JScrollPane jScrollCategoria;
    private javax.swing.JScrollPane jScrollCliente;
    private javax.swing.JScrollPane jScrollProducto;
    private javax.swing.JScrollPane jScrollProveedor;
    private javax.swing.JScrollPane jScrollStock;
    private javax.swing.JScrollPane jScrollUsuario;
    public javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelApellidoCliente;
    private javax.swing.JLabel labelApellidoProv;
    private javax.swing.JLabel labelBuscarCategoria;
    private javax.swing.JLabel labelBuscarCliente;
    private javax.swing.JLabel labelBuscarProd;
    private javax.swing.JLabel labelBuscarProv;
    private javax.swing.JLabel labelBuscarUsuario;
    public javax.swing.JLabel labelCantidadAct;
    public javax.swing.JLabel labelCantidadNew;
    public javax.swing.JLabel labelCantidadProd;
    private javax.swing.JLabel labelCategoriaProd;
    private javax.swing.JLabel labelCedulaCliente;
    private javax.swing.JLabel labelComboProd;
    private javax.swing.JLabel labelDescripcionProd;
    private javax.swing.JLabel labelDireccionProv;
    private javax.swing.JLabel labelEmpresaNit;
    private javax.swing.JLabel labelEmpresaNombre;
    public javax.swing.JLabel labelIvaProd;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreCategoria;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelNombreProd;
    private javax.swing.JLabel labelNombreProv;
    public javax.swing.JLabel labelPasswrord;
    private javax.swing.JLabel labelPrecioCProd1;
    private javax.swing.JLabel labelPrecioVProd;
    private javax.swing.JLabel labelPrecioVProd1;
    private javax.swing.JLabel labelPrecioVProd2;
    private javax.swing.JLabel labelProveedorProd;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTelefono1;
    private javax.swing.JLabel labelTelefonoCliente;
    private javax.swing.JLabel labelTelefonoProv;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelActualizarStock;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelCategoria;
    public javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelEmpresa;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelProveedor;
    private javax.swing.JPanel panelReporte;
    public javax.swing.JPanel panelUsuario;
    private javax.swing.JPanel panelVenta;
    public javax.swing.JTable tableCategoria;
    public javax.swing.JTable tableCliente;
    public javax.swing.JTable tableProducto;
    public javax.swing.JTable tableProveedor;
    public javax.swing.JTable tableStock;
    public javax.swing.JTable tableUsuarios;
    public javax.swing.JTextField textApellido;
    public javax.swing.JTextField textApellidoCliente;
    public javax.swing.JTextField textApellidoProv;
    public javax.swing.JTextField textBuscarCategoria;
    public javax.swing.JTextField textBuscarCliente;
    public javax.swing.JTextField textBuscarProd;
    public javax.swing.JTextField textBuscarProv;
    public javax.swing.JTextField textBuscarUsuario;
    public javax.swing.JTextField textCantidadProd;
    public javax.swing.JTextField textCedulaCliente;
    public javax.swing.JTextField textCorreo;
    public javax.swing.JTextField textDescripcionProd;
    public javax.swing.JTextField textDireccionProv;
    public javax.swing.JTextField textIdCategoria;
    public javax.swing.JTextField textIdCliente;
    public javax.swing.JTextField textIdProd;
    public javax.swing.JTextField textIdProdStock;
    public javax.swing.JTextField textIdProv;
    public javax.swing.JTextField textIdUsuario;
    public javax.swing.JTextField textNombre;
    public javax.swing.JTextField textNombreCategoria;
    public javax.swing.JTextField textNombreCliente;
    public javax.swing.JTextField textNombreProd;
    public javax.swing.JTextField textNombreProv;
    public javax.swing.JTextField textPrecioCProd;
    public javax.swing.JTextField textPrecioVProd;
    public javax.swing.JTextField textStockAct;
    public javax.swing.JTextField textStockNew;
    public javax.swing.JTextField textTelefono;
    public javax.swing.JTextField textTelefonoCliente;
    public javax.swing.JTextField textTelefonoProv;
    public javax.swing.JTextField textUsuario;
    public javax.swing.JLabel tituloPanel;
    public javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
